# .pre-commit-config.yaml
ci:
  # Keep pre-commit.ci enabled & monthly updates
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        name: No commits to main
        args: ['--branch', 'main']
      - id: end-of-file-fixer
      - id: mixed-line-ending
        name: Normalize line endings
        args: ['--fix', 'lf']
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        name: Format Python code with Black
        language_version: python3.12
        files: \.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort Python imports
        language_version: python3.12
        files: \.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Lint Python with Flake8
        additional_dependencies: [flake8-bugbear]
        language_version: python3.12
        args:
          - --max-line-length=79
          - --extend-ignore=E203,E266,W503
        files: ^(src/graph_transformer_benchmark|tests)/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        name: Type-check with mypy
        language_version: python3.12
        args:
          - --ignore-missing-imports
          - --show-error-codes
        files: ^src/graph_transformer_benchmark/.*\.py$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        name: Lint YAML configs
        args:
          - -d
          - >
            {extends: default,
             rules:
               document-start: disable,
               line-length:
                 level: warning}
        files: ^configs/.*\.ya?ml$
