# .pre-commit-config.yaml

ci:
  # https://pre-commit.ci/#configuration
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        name: No commits to master
      - id: end-of-file-fixer
        name: End-of-file fixer
      - id: mixed-line-ending
        name: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: check-toml
        name: Check toml
      - id: check-yaml
        name: Check yaml
        exclude: |
          (?x)^(
              conda/pytorch-geometric/meta.yaml|
              conda/pyg/meta.yaml
          )$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        name: Lint yaml
        args:
          - -d
          - >
            {extends: default,
             rules: {line-length: disable,
                     document-start: disable,
                     truthy: {level: error},
                     braces: {max-spaces-inside: 1}}}

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        name: Upgrade Python syntax
        args: [--py38-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: Remove unused imports and variables
        args:
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --remove-duplicate-keys
          - --ignore-init-module-imports
          - --in-place

  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        name: Format code
        additional_dependencies: [toml]
        args: ["--style", ".style.yapf"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: Sort imports
        args: ["--settings-path", ".isort.cfg"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        name: Check PEP8
        additional_dependencies: [Flake8-pyproject]


exclude: |
  (?x)(
    ^\.venv/|       # ignore virtualenv
    ^data/|         # ignore raw data
    ^notebooks/     # ignore Jupyter notebooks
  )
