data:
  dataset: MUTAG
  batch_size: 32
  num_workers: 4
model:
  type: GraphTransformer
  activation: gelu
  ffn_hidden_dim: null
  use_super_node: false
  hidden_dim: 64
  num_heads: 4
  num_layers: 4
  dropout: 0.1
  seed: 42
  gnn_conv_type: null
  gnn_position: pre
  max_degree: 0
  num_eigenc: 0
  num_svdenc: 0
  num_spatial: 0
  num_edges: 0
  num_hops: 0
  use_batch_norm: false
  use_residual: false
  task: graph
  training:
    mlflow:
      run_name: GraphTransformer-Basic
      description: GraphTransformer with basic settings.
training:
  device: cpu
  lr: 0.001
  epochs: 3
  seed: 42
  n_trials: 10
  val_frequency: 1
  patience: 1
  mlflow:
    experiment_name: test_improved_training-MUTAG
    tracking_uri: file:./mlruns
    log_artifacts: true
    run_name: ${model.type}
    description: null
