data:
  dataset: qm7b
  root: data
  batch_size: 512
  num_workers: 4
  val_ratio: 0.1
  test_ratio: 0.1
  use_subgraph_sampler: true
  sampler:
    type: neighbor
    num_neighbors:
    - 10
    - 10
    disjoint: true
model:
  type: GraphTransformer
  activation: gelu
  ffn_hidden_dim: null
  use_super_node: false
  hidden_dim: 64
  num_heads: 4
  num_layers: 4
  dropout: 0.1
  seed: 42
  gnn_conv_type: gcn
  gnn_position: pre
  max_degree: 32
  num_eigenc: 0
  num_svdenc: 0
  num_spatial: 32
  num_edges: 16
  num_hops: 5
  use_batch_norm: false
  use_residual: false
  with_spatial_bias: true
  with_hop_bias: true
  with_edge_bias: true
  with_degree_enc: true
  with_eig_enc: true
  with_svd_enc: true
  num_eigencs: 8
  num_svdencs: 8
  task: graph
  training:
    mlflow:
      run_name: GraphTransformer-Full-GCN-Pre
      description: 'GraphTransformer with spatial bias, hop bias, and edge bias.

        The model is trained on the graph task with GNN convolution type as GCN.

        The position of GNN is set to pre.

        '
training:
  device: cuda
  lr: 0.001
  epochs: 30
  seed: 42
  n_trials: 10
  val_frequency: 3
  patience: 3
  mlflow:
    experiment_name: errors-GPU
    tracking_uri: file:./mlruns
    log_artifacts: true
    run_name: ${model.type}
    description: null
