# configs/model/common.yaml
objective: classification
hidden_dim: 128
seed: 42
# ── encoder_cfg ────────────────────────────────────────────────────────────
encoder_cfg:
  num_encoder_layers: 4
  num_heads: 4
  dropout: 0.1
  ffn_hidden_dim: 256
  activation: relu
  use_super_node: false

  # attention-bias providers
  bias:
    spatial:
      enabled: false
      num_spatial: 4
    edge:
      enabled: false
      num_edges: 4
    hop:
      enabled: false
      num_hops: 4

  # positional encoders
  positional:
    degree:
      enabled: false
      max_degree: 10
    eig:
      enabled: false
      num_eigenc: 4
      num_eigvec: 4
    svd:
      enabled: false
      num_svdenc: 4

# ── gnn_cfg ─────────────────────────────────────────────────────────────────
gnn_cfg:
  gnn_conv_type: null
  gnn_position: pre
