device: cpu
lr: 1e-3
epochs: 30
seed: 42
n_trials: 10 # Number of Optuna trials
val_frequency: 3
patience: 3

mlflow:
  experiment_name: GraphTransformerBenchmark
  tracking_uri: file:./mlruns
  log_artifacts: true
  run_name: "${model.type}"
  description: null
