# configs/model/variants/basic.yaml
defaults:
  - transformer

task: graph
type: GraphTransformer

training:
  mlflow:
    run_name: GraphTransformer-Basic
    description: |
      GraphTransformer with basic settings. This means no positional encodings
      or bias proviers. Also, no GNN hooks are used.
