# configs/model/variants/basic.yaml
defaults:
  - transformer

task: graph
type: GraphTransformer

training:
  mlflow:
    run_name: GraphTransformer-Basic
    description: |
      GraphTransformer with basic settings.
