# configs/model/variants/bias.yaml
defaults:
  - transformer

encoder_cfg:
  bias:
    spatial:
      enabled: false
      num_spatial: 32
    edge:
      enabled: true
      num_edges: 16
    hop:
      enabled: false
      num_hops: 5

task: graph
type: GraphTransformer

training:
  mlflow:
    run_name: GraphTransformer-Bias-Edge
    description: |
      GraphTransformer with edge bias enabled.
