# configs/model/variants/bias.yaml
defaults:
  - transformer

# turn on all three bias providers
encoder_cfg:
  bias:
    spatial:
      enabled: true
      num_spatial: 32
    edge:
      enabled: true
      num_edges: 16
    hop:
      enabled: true
      num_hops: 5

  positional:
    degree:
      enabled: false
      max_degree: 32
    eig:
      enabled: false
      num_eigenc: 8
    svd:
      enabled: false
      num_svdenc: 8

task: graph
type: GraphTransformer

training:
  mlflow:
    run_name: GraphTransformer-Bias
    description: |
      GraphTransformer with spatial bias, hop bias, and edge bias.
