# configs/model/variants/bias.yaml
defaults:
  - transformer

# turn on all three bias providers
encoder_cfg:
  bias:
    spatial:
      enabled: true
      num_spatial: 32
    edge:
      enabled: true
      num_edges: 16
    hop:
      enabled: true
      num_hops: 5

  positional:
    degree:
      enabled: true
      max_degree: 32
    eig:
      enabled: true
      num_eigenc: 8
    svd:
      enabled: true
      num_svdenc: 8

task: graph
type: GraphTransformer

training:
  mlflow:
    run_name: GraphTransformer-Bias
    description: |
      GraphTransformer with spatial bias, hop bias, and edge bias.
      The model is trained on the graph task with GNN convolution type as GCN.
      The position of GNN is set to pre.
