defaults:
  - transformer

encoder_cfg:
  bias:
    spatial:
      enabled: true
      num_spatial: 32
    edge:
      enabled: true
      num_edges: 16
    hop:
      enabled: true
      num_hops: 5

  positional:
    degree:
      enabled: true
      max_degree: 32

gnn_cfg:
  gnn_conv_type: gcn
  gnn_position: pre

task: graph
type: GraphTransformer

training:
  mlflow:
    run_name: GraphTransformer-Full-GCN-Pre
    description: |
      GraphTransformer with spatial bias, hop bias, and edge bias.
      The model is trained on the graph task with GNN convolution type as GCN.
      The position of GNN is set to pre.
