defaults:
  - transformer

with_spatial_bias: true
num_spatial: 32
with_hop_bias: true
num_hops: 5
with_edge_bias: true
num_edges: 16

with_degree_enc: true
with_eig_enc: true
with_svd_enc: true
max_degree: 32
num_eigencs: 8
num_svdencs: 8

gnn_conv_type: gcn
gnn_position: post

task: graph
type: GraphTransformer

training:
  mlflow:
    run_name: GraphTransformer-Full-GCN-Post
    description: |
      GraphTransformer with spatial bias, hop bias, and edge bias.
      The model is trained on the graph task with GNN convolution type as GCN.
      The position of GNN is set to post.
