defaults:
  - transformer

encoder_cfg:
  bias:
    spatial:
      enabled: false
      num_spatial: 32
    edge:
      enabled: false
      num_edges: 16
    hop:
      enabled: false
      num_hops: 5

  positional:
    degree:
      enabled: true
      max_degree: 32
    eig:
      enabled: true
      num_eigenc: 8
    svd:
      enabled: true
      num_svdenc: 8
task: graph
type: GraphTransformer
training:
  mlflow:
    run_name: GraphTransformer-PositionalEncoding
    description: |
      GraphTransformer with all positional encodings enabled. This includes
      degree, eigendecomposition, and SVD encodings.
