defaults:
  - transformer

encoder_cfg:
  positional:
    degree:
      enabled: true
      max_degree: 32

task: graph
type: GraphTransformer
training:
  mlflow:
    run_name: GraphTransformer-PositionalEncoding
    description: |
      GraphTransformer with degree encodings enabled.
