defaults:
  - transformer

encoder_cfg:
  positional:
    eig:
      enabled: true
      num_eigenc: 8
task: graph
type: GraphTransformer
training:
  mlflow:
    run_name: GraphTransformer-PositionalEncoding-Eigendecomposition
    description: |
      GraphTransformer with eigendecomposition encodings enabled
