defaults:
  - transformer

encoder_cfg:
  positional:
    degree:
      enabled: false
      max_degree: 32
    eig:
      enabled: true
      num_eigenc: 8
    svd:
      enabled: false
      num_svdenc: 8
task: graph
type: GraphTransformer
training:
  mlflow:
    run_name: GraphTransformer-PositionalEncoding-Eigendecomposition
    description: |
      GraphTransformer with eigendecomposition encodings enabled
