defaults:
  - transformer

encoder_cfg:
  positional:
    svd:
      enabled: true
      num_svdenc: 8
task: graph
type: GraphTransformer
training:
  mlflow:
    run_name: GraphTransformer-PositionalEncoding-SVD
    description: |
      GraphTransformer with SVD encodings enabled
