name: CI Tests

"on":
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-normal:
    name: Run Normal Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run normal tests
        run: |
          poetry run pytest -m "not slow" \
            --cov=src \
            --cov-report=term-missing \
            --cov-data-file=.coverage.normal

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-normal
          path: .coverage.normal
          retention-days: 1

  test-slow:
    name: Run Slow Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run slow tests
        run: |
          poetry run pytest -m slow \
            --cov=src \
            --cov-report=term-missing \
            --cov-data-file=.coverage.slow

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-slow
          path: .coverage.slow
          retention-days: 1

  sonar:
    name: SonarQube Analysis
    needs: [test-normal, test-slow]  # Wait for both test jobs to complete
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Download normal coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-normal
          path: .

      - name: Download slow coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-slow
          path: .

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install coverage
        run: pip install coverage

      - name: Combine coverage data
        run: |
          coverage combine .coverage.normal .coverage.slow
          coverage xml -o coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
