name: CI Tests

"on":
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-normal:
    name: Run Normal Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run normal tests
        run: |
          poetry run pytest -m "not slow" \
            --cov=src \
            --cov-report=xml:coverage-normal.xml \
            --cov-report=term-missing

      - name: Upload normal coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-normal.xml
          fail_ci_if_error: false

  test-slow:
    name: Run Slow Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run slow tests
        run: |
          poetry run pytest -m slow \
            --cov=src \
            --cov-report=xml:coverage-slow.xml \
            --cov-report=term-missing

      - name: Upload slow coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-slow.xml
          fail_ci_if_error: false
